name: Auto Merge to Development

on:
  push:
    branches-ignore:
      - development

permissions:
  contents: write

jobs:
  merge-to-development:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Attempt to merge into development
        run: |
          git checkout development
          git merge origin/${{ github.ref_name }} --no-edit || echo "Merge conflict, skipping..."

      - name: Push to development if merge succeeded
        if: success()
        run: |
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} development
